apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ui
spec:
  rules:
    - http:
        paths:
          - path: /jaeger
            pathType: Prefix
            backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
  ingressClassName: nginx
