resources:
  - https://github.com/jaegertracing/jaeger-operator/releases/download/v1.33.0/jaeger-operator.yaml

images:
  - name: quay.io/jaegertracing/jaeger-operator
    newName: quay.mirrors.ustc.edu.cn/jaegertracing/jaeger-operator
  - name: gcr.io/kubebuilder/kube-rbac-proxy
    newName: quay.mirrors.ustc.edu.cn/brancz/kube-rbac-proxy